---
- name: place bash_profile file
  copy:
    src: bash_profile
    dest: "{{ ansible_env.HOME }}/.bash_profile"

- name: place bashrc file
  copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"

- name: place work bashrc file
  copy:
    src: work-bashrc
    dest: "{{ ansible_env.HOME }}/.profile-work/bashrc"
  when: profile == "work"

- name: place ctags file
  copy:
    src: ctags
    dest: "{{ ansible_env.HOME }}/.ctags"

- name: create work go-jira dir
  file:
    type: directory
    path: "{{ ansible_env.HOME }}/.jira.d"
  when: profile == "work"

- name: place go-jira config file
  copy:
    src: go-jira-config.yml
    dest: "{{ ansible_env.HOME }}/.jira.d/config.yml"
  when: profile == "work"

- name: create bash completion dir
  file:
    type: directory
    path: "{{ ansible_env.HOME }}/.bash-completion.d"

- name: place bash terragrunt completion file
  copy:
    src: terragrunt.sh
    dest: "{{ ansible_env.HOME }}/.bash-completion.d/terragrunt.sh"

- name: place bash terraform completion file
  copy:
    src: terraform.sh
    dest: "{{ ansible_env.HOME }}/.bash-completion.d/terraform.sh"

