---
- hosts: all
  vars_files:
    - config-work.yml
  vars:
    profile: work
    homebrew_cask_appdir: "{{ ansible_env.HOME }}/Applications"
  pre_tasks:
    - name: create work profile dir
      file:
        path: "{{ ansible_env.HOME }}/.profile-work"
        state: directory
  roles:
    # NOTE: I shouldn't have to check for true explicitly, but it doesn't work without it
    - role: elliotweiser.osx-command-line-tools
      tags: ['command-line-tools']
      when: ansible_distribution == 'MacOSX' and configure_command_line_tools == true
    - role: geerlingguy.mac.dock
      tags: ['dock']
      when: ansible_distribution == 'MacOSX' and configure_dock == true
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: ansible_distribution == 'MacOSX' and configure_homebrew == true
    - role: bash
      tags: ['bash']
    - role: bin
      tags: ['bin']
    - role: git
      tags: ['git']
    - role: postgres
      tags: ['postgres']
    - role: python
      tags: ['python']
    - role: tmux
      tags: ['tmux']
    - role: vim
      tags: ['vim']

