# ex: ts=2 sw=2 et filetype=sh

export BASH_SILENCE_DEPRECATION_WARNING=1

case "$-" in
  *i*) (>&2 echo 'this shell is interactive') ;;
  *)	 (>&2 echo 'this shell is NOT interactive') ;;
esac

test -e "${HOME}/.iterm2_shell_integration.bash" && . "${HOME}/.iterm2_shell_integration.bash"

export LANG=en_US.UTF-8
export LC_ALL=$LANG

export TERM='xterm-256color'

export CLICOLOR=1

stty stop undef

# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi

[ -n "$PS1" ] && \
  [ "$(which tinty)" ] && \
    tinty apply base16-tomorrow-night

