# shellcheck shell=bash

export BASH_CONF='bashrc'

export BASH_SILENCE_DEPRECATION_WARNING=1

if [ -n "${SESSION_DEBUG:-}" ]; then
  case "$-" in
    *i*) (>&2 echo 'bashrc sourced in interactive shell') ;;
    *)   (>&2 echo 'bashrc sourced in noninteractive shell') ;;
  esac
fi

export HOMEBREW_PREFIX="/usr/local"
if [ "$(uname -p)" == 'arm' ]; then
  export HOMEBREW_PREFIX="/opt/homebrew"
fi

export HOMEBREW_CELLAR="${HOMEBREW_PREFIX}/Cellar"
export HOMEBREW_REPOSITORY="${HOMEBREW_PREFIX}/Homebrew"
export HOMEBREW_BIN="${HOMEBREW_PREFIX}/bin"
export HOMEBREW_SBIN="${HOMEBREW_PREFIX}/sbin"
PATH="${HOMEBREW_BIN}:${HOMEBREW_SBIN}${PATH+:$PATH}"
export MANPATH="${HOMEBREW_PREFIX}/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="${HOMEBREW_PREFIX}/share/info:${INFOPATH:-}"

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_UPGRADE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_ANALYTICS=1

# completions
if type brew &>/dev/null; then
  if [ -n "$BASH_VERSION" ]; then
    if [ "${BASH_VERSINFO[0]}" -gt 4 ] ||
        [ "${BASH_VERSINFO[0]}" -eq 4 -a "${BASH_VERSINFO[1]}" -ge 2 ]; then
      if [ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]; then
        # shellcheck disable=SC1091
        . "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
      else
        for completion in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
          # shellcheck disable=SC1090
          [ -r "$completion" ] && . "$completion"
        done
      fi

      if [ -d "${HOME}/bash-completion.d" ]; then
        for completion in "${HOME}/bash-completion.d/"*; do
          # shellcheck disable=SC1090
          [ -r "$completion" ] && . "$completion"
        done
      fi
    else
      (>&2 echo "The bash version you are running, ${BASH_VERSION}, is insufficient. Did you make sure to chsh?")
      (>&2 echo "Try editing /etc/shells and running chsh")
      return
    fi
  else
    (>&2 echo "Not running in Bash (maybe Zsh or another shell).")
  fi
fi

if type sqlc &>/dev/null; then
  # shellcheck disable=SC1090
  . <(sqlc completion bash)
fi

# Jetbrains Toolbox App
PATH="${PATH}:${HOME}/Library/Application Support/JetBrains/Toolbox/scripts"

# 1password
export SSH_AUTH_SOCK="${HOME}/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

export XDG_CONFIG_HOME="$HOME/.config"

# shellcheck disable=SC1091
. "${XDG_CONFIG_HOME}/op/plugins.sh"

# set limits per session just in case
ulimit -n 65536
ulimit -u 2048

export LANG=en_US.UTF-8
export LC_ALL=$LANG

export JAVA_HOME
JAVA_HOME="$(/usr/libexec/java_home)"

# # for a specific java version
# export JAVA_VERSION=21.0.9
# JAVA_HOME="$(/usr/libexec/java_home -v ${JAVA_VERSION})"

# go install golang.org/dl/go1.23.5@latest
# go1.23.5 download

export OpenCV_DIR="${HOMEBREW_PREFIX}/Cellar/opencv/2.4.9"

export EDITOR='nvim'

export GITHUB_TOKEN
GITHUB_TOKEN="$(tr -d '\n' < "$HOME/.github-personal-access-token")"
export HOMEBREW_GITHUB_API_TOKEN="$GITHUB_TOKEN"

# colorize the Terminal
export CLICOLOR=1;

# only stop output flow control in interactive shells
case "$-" in
  *i*) stty stop undef ;;
esac

export CC=/usr/bin/clang
export CXX=/usr/bin/clang++

# direnv
eval "$(direnv hook bash)"

alias sbp='. ${HOME}/.bash_profile'
alias sbrc='. ${HOME}/.bashrc'
alias ll='ls -al'
alias cs='printf "\033c"'
# shellcheck disable=SC2142 # these aren't positional params
alias mkt="make -qp | awk -F':' '/^[a-zA-Z0-9][^\$\#\\/\\t=]*:([^=]|$)/ {split(\$1,A,/ /);for(i in A)print A[i]}' | sort -u"
alias sort-ips="sort -t . -k 3,3n -k 4,4n"
alias review='rg -A 3 "(FIX|NOTE|BUG|REVIEW|TODO|HACK|OPTIMIZE):?\s+"'
alias tg-clean='find . \( \( -type d -name ".terragrunt-cache" \) -or \( -type f -name "terragrunt-debug.tfvars.json" \) \) -exec rm -rf "{}" \+ -print'
alias tgs-clean='find . -type d -name ".terragrunt-stack" -exec rm -rf "{}" \+ -print'
alias tf-clean='find . -type d -name ".terraform" -exec rm -rf "{}" \+ -print'
alias tf-lock-clean='find . -type f -name ".terraform.lock.hcl" -exec rm -rf "{}" \+ -print'

# git
if [ -f "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh" ]; then
  # shellcheck disable=SC1091
  . "${HOMEBREW_PREFIX}/etc/bash_completion.d/git-prompt.sh"
  PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
fi

# check out all remote branches
# git branch -a | grep -v HEAD | perl -ne 'chomp($_); s|^\*?\s*||; if (m|(.+)/(.+)| && not $d{$2}) {print qq(git branch --track $2 $1/$2\n)} else {$d{$_}=1}' | csh -xfs

# only use my git shortcuts in interactive sessions
case "$-" in
  *i*)
  alias gst='git status'
  alias gsts='git status -s'
  _comp_gst() {
    local __git_cmd_idx=0
    _git_status
  } && __git_complete gst _comp_gst \
    && __git_complete gsts _comp_gst
  alias gdf='git diff'
  __git_complete gdf _git_diff
  alias gdfw='git diff --ws-error-highlight=all'
  __git_complete gdfw _git_diff
  alias gdfc='git diff --cached'
  __git_complete gdfc _git_diff
  alias gdfcw='git diff --cached --ws-error-highlight=all'
  __git_complete gdfcw _git_diff
  alias gf='git fetch'
  __git_complete gf _git_fetch
  alias gfa='git fetch --all'
  __git_complete gfa _git_fetch
  alias gpul='git pull'
  __git_complete gpul _git_pull
  alias gpsh='git push'
  __git_complete gpsh _git_push
  alias gpshh='git push -u origin HEAD'
  __git_complete gpshh _git_push
  alias gfp='git fetch && git pull'
  alias grv='git remote -v'
  alias gaa='git add .'
  __git_complete gaa _git_add
  alias ga='git add'
  alias gau='git add -u'
  _comp_ga() {
    local __git_cmd_idx=0
    _git_add
  } && __git_complete ga _comp_ga \
    && __git_complete gau _comp_ga
  alias gl='git log'
  __git_complete gl _git_log
  alias glp='git log -p'
  __git_complete glp _git_log
  alias gc='git commit'
  __git_complete gc _git_commit
  alias gcm='git commit -m'
  __git_complete gcm _git_commit
  alias gco='git checkout'
  alias gcob='git checkout -b'
  ## https://github.com/scop/bash-completion/issues/545
  # __git_complete gco _git_checkout
  _comp_gco() {
    local __git_cmd_idx=0
    _git_checkout
  } && __git_complete gco _comp_gco \
    && __git_complete gcob _comp_gco
  alias gmrg='git merge'
  __git_complete gmrg _git_merge
  alias gbr='git branch'
  _comp_gbr() {
    local __git_cmd_idx=0
    _git_branch
  } && __git_complete gbr _comp_gbr
  alias grb='git rebase'
  __git_complete grb _git_rebase
  alias grst='git reset'
  __git_complete grst _git_reset
  alias gsth='git stash'
  __git_complete gsth _git_stash
  ;;
esac

export PAGER=less
export LESS="-NiSR"
# shellcheck disable=SC2139 # we want this to expand when defined
alias less="less ${LESS}"

complete -C aws_completer aws

export AWS_PAGER=

export HISTFILESIZE=9999999
export HISTSIZE=9999999

# no duplicate entries
export HISTCONTROL=ignoredups:erasedups:ignorespace

# append to history, don't overwrite it
shopt -s histappend
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

GCP_SDK_HOME="/opt/google/google-cloud-sdk"
PATH="${PATH}:${GCP_SDK_HOME}/bin"

# The next line updates PATH for the Google Cloud SDK.
# shellcheck disable=SC1091
[ -f "${GCP_SDK_HOME}/path.bash.inc" ] && . "${GCP_SDK_HOME}/path.bash.inc"

# The next line enables shell command completion for gcloud.
# shellcheck disable=SC1091
[ -f "${GCP_SDK_HOME}/completion.bash.inc" ] && . "${GCP_SDK_HOME}/completion.bash.inc"

gcloud_docker () {
  local key credpath entrypoint entrypointpath
  key="$1"
  credpath=/root/credentials.json
  entrypoint="$(mktemp)"
  entrypointpath=/root/entrypoint.sh
  cat > "$entrypoint" <<'EOF'
#!/bin/bash
set -o errexit
set -o xtrace
gcloud auth activate-service-account --key-file=/root/credentials.json
exec "$@"
EOF
  chmod 711 "$entrypoint"
  touch "${HOME}/.gcloud-docker-bash_history"
  chmod 600 "${HOME}/.gcloud-docker-bash_history"
  docker run -it --rm -w "/root" \
    -v "${HOME}/.gcloud-docker-bash_history:/root/.bash_history" \
    -v "${HOME}/.ssh:/root/.ssh:ro" \
    -v "${key}:${credpath}:ro" \
    -v "${entrypoint}:${entrypointpath}:ro" \
    --entrypoint "$entrypointpath" google/cloud-sdk /bin/bash
}

# rancher desktop
if [ -d "${HOME}/.rd/bin/docker" ]; then
  PATH="${HOME}/.rd/bin:${PATH}"
fi

# docker desktop
if [ -d "${HOME}/.docker/bin" ]; then
  PATH="${HOME}/.docker/bin:${PATH}"
fi

# kubernetes
if type kubectl &>/dev/null; then
  # shellcheck disable=SC1090
  source <(kubectl completion bash)
fi

# helm
export HELM_HOME="${HOME}/.helm"

# tmux
tmux_colors() {
  for i in {0..255}; do
    printf "\x1b[38;5;%smcolour%s\x1b[0m\n" "$i" "$i"
  done
}
alias tmux-colors=tmux_colors

_tma() {
  local -r tmux_sessions="$(tmux ls -F '#S' | xargs)"
  mapfile -t COMPREPLY < <(compgen -W "$tmux_sessions" -- "${COMP_WORDS[COMP_CWORD]}")
}
tma() {
  tmux attach -t "$1"
}
complete -F _tma tma
alias tmls='tmux ls'

alias sha1sum="shasum"
alias sha256sum="shasum -a 256"
alias sha512sum="shasum -a 512"
alias diff-favorite="diff --color=always --exclude=.git -r -W 250 -y --suppress-common-lines"

# tmpfile=$( mktemp -t transferXXX ); if tty -s; then basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g'); curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> $tmpfile; else curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> $tmpfile ; fi; cat $tmpfile; printf "\n"; rm -f $tmpfile; }

alias ssh-no-config-or-agent="ssh -F /dev/null -o IdentityAgent=none -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias scp-no-config-or-agent="scp -F /dev/null -o IdentityAgent=none -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias ssh-force-password="ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no"
alias scp-force-password="scp -o PreferredAuthentications=password -o PubkeyAuthentication=no"
alias gh="PAGER= gh"

export ANSIBLE_NOCOWS=1

export DOTNET_CLI_TELEMETRY_OPTOUT=1

export VAGRANT_DEFAULT_PROVIDER=virtualbox

## krew bin
if type krew &>/dev/null; then
  PATH="${PATH}:${HOME}/.krew/bin"
fi

## temp bin
PATH="/opt/bin:${PATH}"

## vim iced
# PATH=${PATH}:${HOME}/.janus/vim-iced/bin

# Postgres.app
PG_APP_BIN_PATH="/Applications/Postgres.app/Contents/Versions/latest/bin"
[ -d "$PG_APP_BIN_PATH" ] && PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:${PATH}"

export NVM_DIR="$HOME/.nvm"
# this loads nvm
# shellcheck disable=SC1091
[ -s "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh" ] && . "${HOMEBREW_PREFIX}/opt/nvm/nvm.sh"
# this loads nvm bash_completion
# shellcheck disable=SC1091
[ -s "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm" ] && . "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm"

if command -v goenv 1>/dev/null 2>&1; then
  # check if goenvrc contains the `export GOENV_PATH_ORDER=front` line and if not, add it
  if ! grep -q "export GOENV_PATH_ORDER=front" "${HOME}/.goenvrc" 2>/dev/null; then
    echo "export GOENV_PATH_ORDER=front" >> "${HOME}/.goenvrc"
  fi
  export GOENV_AUTOMATICALLY_DETECT_VERSION=1
  eval "$(goenv init -)"
fi

alias python=/usr/bin/python3
export PYTHONSTARTUP="${HOME}/.pythonrc.py"
export PYENV_ROOT="${HOME}/.pyenv"

if command -v pyenv 1>/dev/null 2>&1; then
  [ -d "${PYENV_ROOT}/bin" ] && export PATH="${PYENV_ROOT}/bin:${PATH}"
  eval "$(pyenv init - bash)"
fi

if [ -f "${HOMEBREW_PREFIX}/opt/gnu-getopt/bin/getopt" ]; then
  PATH="${HOMEBREW_PREFIX}/opt/gnu-getopt/bin:${PATH}"
fi

## clean the PATH
clean_path() {
  if [ -n "$PATH" ]; then
    old_PATH=$PATH:
    new_PATH=

    while [ -n "$old_PATH" ]; do
      entry=${old_PATH%%:*}    # the first remaining entry

      if [ -z "${entry:-}" ]; then
        # empty entry, skip it
        old_PATH=${old_PATH#*:}
        continue
      fi

      case $new_PATH: in
        *:"$entry":* | "$entry":* | *:"$entry") ;; # already there
        *) new_PATH=$new_PATH:$entry ;; # not there yet
      esac

      old_PATH=${old_PATH#*:}
    done

    export PATH=${new_PATH#:}
    unset  old_PATH new_PATH entry
  fi
}

export TINTY_DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/tinted-theming/tinty"

# this does not seem to work in iterm2 any more...
# # Tinty isn't able to apply environment variables to your shell due to
# # the way shell sub-processes work. This is a work around by running
# # Tinty through a function and then executing the shell scripts.
# tinty_source_shell_theme() {
#   local newer_file=$(mktemp)
#   tinty "$@"
#   local subcommand="$1"
#
#   if [ "$subcommand" = "apply" ] || [ "$subcommand" = "init" ]; then
#     while read -r script; do
#       # shellcheck disable=SC1090
#       . "$script"
#     done < <(find "$TINTY_DATA_DIR" -maxdepth 1 -type l -name '*.sh' -newer "$newer_file")
#   fi
# }
#
# if command -v tinty 1>/dev/null 2>&1 && ! alias tinty >/dev/null 2>&1; then
#   tinty_source_shell_theme "init" > /dev/null 2>&1
#
#   alias tinty=tinty_source_shell_theme
# fi

# only run if the shell is running in iTerm2.
if [ "$TERM_PROGRAM" = "iTerm.app" ]; then
  osascript "${HOME}/Library/Application Support/iTerm2/Scripts/AutoLaunch.scpt"
fi

pth() {
  echo "$PATH" | tr ':' '\n' | xargs -I'{}' printf '\- {}\n'
}

if [ -f "${HOME}/.profile-work/bashrc" ]; then
  export PROFILE=work
  # shellcheck disable=SC1091
  source "${HOME}/.profile-work/bashrc"
# TODO: fix this
# else
#   export HOMEBREW_GITHUB_API_TOKEN="$(cat $HOME/.github-personal-access-token | tr -d '\n')"
#   export GITHUB_TOKEN="$(cat $HOME/.github-personal-access-token | tr -d '\n')"
fi

clean_path

# make sure home bin is first
export PATH="${HOME}/bin:${HOME}/.local/bin:${PATH}"

# shellcheck disable=SC1091
test -r "${HOME}/.iterm2_shell_integration.bash" && . "${HOME}/.iterm2_shell_integration.bash"

# ex: ts=2 sw=2 et filetype=sh

