---
- name: create .vim dir
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    state: directory

- name: create .vim child dirs
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
  loop:
    - "_backup"
    - "_temp"
    - "_undo"
    - "plugged"

- name: sync .vim dir
  command: rsync -aP "{{ role_path }}/files/dotvim/" "{{ ansible_env.HOME }}/.vim/"

- name: PlugInstall
  command: vim -c ":PlugInstall | qa!"

- name: place .ideavimrc file
  copy:
    src: dotideavimrc
    dest: "{{ ansible_env.HOME }}/.ideavimrc"

